/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'webyog' at '31/7/15 12:03 AM' with Gradle 2.2.1
 *
 * @author webyog, @date 31/7/15 12:03 AM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
